In [1]:
import pandas as pd
customer = pd.read_csv(r"C:\Users\User\Desktop\E-Commerce Data Lakaehouse with AI-Powered Self-Healing Pipelines\raw_data\customers\customers_initial.csv")

In [2]:
customer.head()

,customer_id,first_name,last_name,email,phone,address,city,country,signup_date,last_updated
0,CUST-E251FEFB,Dennis,Moreno,dennis.moreno6bb0@example.com,604-439-5248x26407,65438 Kevin Manors,East Frankborough,Georgia,2021-12-07,2025-09-08 22:28:15
1,CUST-0FC04045,Brianna,Miller,brianna.miller48f2@example.com,543-648-4529x804,027 Hansen Vista Apt. 885,East Josephhaven,Kazakhstan,2022-05-22,2025-09-08 22:28:15
2,CUST-2E48FF64,Michael,Riley,michael.riley81ba@example.com,001-982-810-7679x13408,18967 Cole Crossing,Port Nicole,Lesotho,2024-07-30,2025-09-08 22:28:15
3,CUST-D7C4AFB2,Charles,Morales,charles.morales288b@example.com,517-412-1704x756,3030 Miller Station Suite 337,Michaelburgh,Reunion,2024-01-01,2025-09-08 22:28:15
4,CUST-572EE1F3,Katie,Kline,katie.kline3e9c@example.com,+1-415-600-8905,63152 Timothy Loop,Allenfort,Albania,2022-07-21,2025-09-08 22:28:15

In [4]:
import pandas as pd
deliveries  = pd.read_csv(r"C:\Users\User\Desktop\E-Commerce Data Lakaehouse with AI-Powered Self-Healing Pipelines\raw_data\deliveries\deliveries_initial.csv") 
deliveries.head()

,delivery_id,order_id,transaction_id,customer_id,customer_name,product_id,product_name,total_amount,payment_method,delivery_address,delivery_city,delivery_country,delivery_date,delivery_status,last_updated
0,a7a68f8c-d7c4-42e0-ba01-5aef4eb905bd,ORD-43B855DF,TXN-3D470C3EB548,CUST-B36B8E4E,Morgan Woods,PRD-38362079,Clothing - Walk 772,537.35,UPI,635 Doyle Park Suite 340,North Joseph,Burkina Faso,2022-03-25,Failed,2025-09-08 22:39:04
1,7b573eff-4bd0-4bc5-a09c-87a35c103329,ORD-4BAA8377,TXN-BCBB1008612C,CUST-D09505AC,Denise Mcdowell,PRD-C61CFACD,Home & Kitchen - Peace 156,3066.62,Debit Card,764 Jackson Station Suite 901,New Samanthaberg,Somalia,2021-07-19,Delivered,2025-09-08 22:39:04
2,7ea25d2e-9ded-45a5-88f7-eb414f3441c1,ORD-620B0DE7,TXN-1F616FC209BB,CUST-72DDB465,Erin David,PRD-C5974904,Groceries - System 972,1983.27,PayPal,737 Holt Lights,East Jamesbury,Mexico,2022-06-19,In Transit,2025-09-08 22:39:04
3,5c9ca7ca-f256-4192-926d-24e62af1ea9b,ORD-B9B39560,TXN-264BF45FD6AA,CUST-1CA5AF40,Alexander Caldwell,PRD-94A76C71,Office Supplies - Image 430,3030.80,Cash,66013 Anderson Island Apt. 844,Keithfort,Andorra,2023-05-13,Delivered,2025-09-08 22:39:04
4,4f5b182b-dd3f-4d3a-9585-5b66070d848b,ORD-EFE4EA31,TXN-38A022010B56,CUST-59125B29,Kelsey Warner,PRD-9A8697A8,Home & Kitchen - Dark 979,1925.94,Cash,49788 Barrett Drive Suite 029,Coleborough,Tunisia,2025-05-28,Delivered,2025-09-08 22:39:04

In [5]:
import pandas as pd
orders = pd.read_csv(r"C:\Users\User\Desktop\E-Commerce Data Lakaehouse with AI-Powered Self-Healing Pipelines\raw_data\orders\orders_initial.csv")
orders.head()

,order_id,transaction_id,customer_id,product_id,quantity,total_amount,order_date,payment_method,order_status,last_updated
0,ORD-43B855DF,TXN-3D470C3EB548,CUST-B36B8E4E,PRD-38362079,1,537.35,2022-03-22,UPI,Shipped,2025-09-08 22:30:58
1,ORD-4BAA8377,TXN-BCBB1008612C,CUST-D09505AC,PRD-C61CFACD,2,3066.62,2021-07-10,Debit Card,Shipped,2025-09-08 22:30:58
2,ORD-620B0DE7,TXN-1F616FC209BB,CUST-72DDB465,PRD-C5974904,3,1983.27,2022-06-18,PayPal,Delivered,2025-09-08 22:30:58
3,ORD-B9B39560,TXN-264BF45FD6AA,CUST-1CA5AF40,PRD-94A76C71,2,3030.80,2023-05-06,Cash,Pending,2025-09-08 22:30:58
4,ORD-EFE4EA31,TXN-38A022010B56,CUST-59125B29,PRD-9A8697A8,2,1925.94,2025-05-20,Cash,Cancelled,2025-09-08 22:30:58

In [6]:
import pandas as pd
products = pd.read_csv(r"C:\Users\User\Desktop\E-Commerce Data Lakaehouse with AI-Powered Self-Healing Pipelines\raw_data\products\products_initial.csv")
products.head()

,product_id,name,category,price,stock_quantity,created_at,last_updated
0,PRD-77D5E51E,Automotive - Major 122,Automotive,450.01,997,2022-03-30,2025-09-08 22:27:07
1,PRD-AF563BC5,Groceries - Indeed 584,Groceries,1723.28,614,2022-05-27,2025-09-08 22:27:07
2,PRD-3D3CD280,Automotive - Next 380,Automotive,6.73,933,2021-10-10,2025-09-08 22:27:07
3,PRD-E94F2BB9,Toys - Until 982,Toys,1960.36,564,2020-11-30,2025-09-08 22:27:07
4,PRD-7584BD5A,Toys - Result 543,Toys,1728.54,748,2025-04-09,2025-09-08 22:27:07